version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: /home/sam/comics
        target: /comics
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
    ports:
      - 10.242.53.141:8085:8080
      - 127.0.0.1:8085:8080
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    # environment:
    #   - <ENV_VAR>=<extra configuration>
    restart: unless-stopped
