version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - USER=username #optional
      - PASS=password #optional
      - PEERPORT=51413 #optional
    volumes:
      - ./config:/config
      - /home/sam/downloads:/downloads
      - ./watch:/watch
    ports:
      - 127.0.0.1:9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
